//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancePaynemts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvancePaynemts()
        {
            this.PlanOrders = new HashSet<PlanOrders>();
        }
    
        public int id { get; set; }
        public int id_PZ_Currency { get; set; }
        public double revenue { get; set; }
        public double ssm { get; set; }
        public double ssr { get; set; }
        public double ik { get; set; }
        public double ipk { get; set; }
        public double pi { get; set; }
        public double nop { get; set; }
        public double price { get; set; }
        public double rate { get; set; }
        public double vat { get; set; }
        public double ssrf { get; set; }
        public double ssmToBYN { get; set; }
        public double ssmProduct { get; set; }
        public string id_AspNetUsersCreater { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanOrders> PlanOrders { get; set; }
    }
}
