//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveCDQuestionCorr
    {
        public int id { get; set; }
        public int id_ApproveCDQuestions { get; set; }
        public System.DateTime datetimeCreate { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string textData { get; set; }
    
        public virtual ApproveCDQuestions ApproveCDQuestions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
