//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveCDTasks
    {
        public int id { get; set; }
        public int id_ApproveCDOrders { get; set; }
        public System.DateTime dateEvent { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public string id_AspNetUsers { get; set; }
    
        public virtual ApproveCDOrders ApproveCDOrders { get; set; }
    }
}
