//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveCDTasks
    {
        public int id { get; set; }
        public int id_ApproveCDOrders { get; set; }
        public System.DateTime dateEvent { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public string id_AspNetUsers { get; set; }
    
        public virtual ApproveCDOrders ApproveCDOrders { get; set; }
    }
}
