//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveCDActions
    {
        public int id { get; set; }
        public int id_ApproveCDVersions { get; set; }
        public int id_RKD_VersionWork { get; set; }
        public string id_AspNetUsers { get; set; }
        public System.DateTime datetime { get; set; }
        public double counterKBM { get; set; }
        public double counterKBE { get; set; }
    
        public virtual ApproveCDVersions ApproveCDVersions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TypeRKD_Mail_Version TypeRKD_Mail_Version { get; set; }
    }
}
