//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveCDQuestionCorr
    {
        public int id { get; set; }
        public int id_ApproveCDQuestions { get; set; }
        public System.DateTime datetimeCreate { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string textData { get; set; }
    
        public virtual ApproveCDQuestions ApproveCDQuestions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
