//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        public string LPNTR { get; set; }
        public int COPY { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public string NAME { get; set; }
        public string SUBENTRY { get; set; }
        public string SUBVERSION { get; set; }
    }
}
