//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicPlan
    {
        public string Месяц { get; set; }
        public string quart { get; set; }
        public string Неделя { get; set; }
        public Nullable<int> year { get; set; }
        public string C__заказа { get; set; }
        public Nullable<System.Guid> ProjectUID { get; set; }
        public string TaskName { get; set; }
        public Nullable<short> TaskPercentWorkCompleted { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskFinishDate { get; set; }
        public Nullable<decimal> RKD { get; set; }
        public Nullable<decimal> TaskActualWork { get; set; }
        public Nullable<decimal> TaskActualRegularWork { get; set; }
        public Nullable<decimal> TaskActualOvertimeWork { get; set; }
        public Nullable<decimal> TaskWorkVariance { get; set; }
        public Nullable<decimal> TaskWork { get; set; }
        public Nullable<decimal> TaskResourcePlanWork { get; set; }
        public Nullable<decimal> TaskRemainingWork { get; set; }
        public Nullable<decimal> TaskRemainingRegularWork { get; set; }
        public Nullable<decimal> TaskRemainingOvertimeWork { get; set; }
        public Nullable<decimal> TaskRegularWork { get; set; }
        public Nullable<bool> TaskIsCritical { get; set; }
        public Nullable<bool> TaskIsExternal { get; set; }
        public string ЭтапПроизводства_Прочие_ { get; set; }
        public string TaskWBS { get; set; }
        public Nullable<System.DateTime> TimeByDay { get; set; }
        public Nullable<decimal> AssignmentWork { get; set; }
        public string СДРес { get; set; }
        public Nullable<decimal> AssignmentRemainingWork { get; set; }
        public Nullable<decimal> AssignmentRegularWork { get; set; }
        public Nullable<decimal> AssignmentRemainingOvertimeWork { get; set; }
        public int id { get; set; }
    }
}
