//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cable
    {
        public string ENTRY { get; set; }
        public int COPY { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NODENO { get; set; }
        public Nullable<float> CrossSection { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Flags { get; set; }
        public string SUBENTRY { get; set; }
        public string SUBVERSION { get; set; }
        public Nullable<float> OuterDia { get; set; }
    }
}
