//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisAccruedG
    {
        public int id { get; set; }
        public string id_AspNetUsers { get; set; }
        public double accruedPlan { get; set; }
        public double accruedFact { get; set; }
        public double withheldPlan { get; set; }
        public double withheldFact { get; set; }
        public double accruedTotalPlan { get; set; }
        public double accruedTotalFact { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
