//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisWageFund
    {
        public int id { get; set; }
        public double wageFundMPlan { get; set; }
        public double wageFundMFact { get; set; }
        public double wageFundEPlan { get; set; }
        public double wageFundEFact { get; set; }
        public double wageFundWorkerMPlan { get; set; }
        public double wageFundWorkerMFact { get; set; }
        public double wageFundWorkerEPlan { get; set; }
        public double wageFundWorkerEFact { get; set; }
        public double wageFundManagerMPlan { get; set; }
        public double wageFundManagerMFact { get; set; }
        public double wageFundManagerEPlan { get; set; }
        public double wageFundManagerEFact { get; set; }
        public double wageFundOverflowsMPlan { get; set; }
        public double wageFundOverflowsMFact { get; set; }
        public double wageFundOverflowsEPlan { get; set; }
        public double wageFundOverflowsEFact { get; set; }
        public double wageFundOverflowsWorkerMPlan { get; set; }
        public double wageFundOverflowsWorkerMFact { get; set; }
        public double wageFundOverflowsWorkerEPlan { get; set; }
        public double wageFundOverflowsWorkerEFact { get; set; }
        public double wageFundOverflowsManagerMPlan { get; set; }
        public double wageFundOverflowsManagerMFact { get; set; }
        public double wageFundOverflowsManagerEPlan { get; set; }
        public double wageFundOverflowsManagerEFact { get; set; }
        public double wageFundGMPlan { get; set; }
        public double wageFundGMFact { get; set; }
        public double wageFundGEPlan { get; set; }
        public double wageFundGEFact { get; set; }
    }
}
