//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisCoefManager
    {
        public int id { get; set; }
        public string id_CMKO_PeriodResult { get; set; }
        public string id_AspNetUsers { get; set; }
        public double coef { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CMKO_PeriodResult CMKO_PeriodResult { get; set; }
    }
}
