//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_Optimization
    {
        public int id { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string id_AspNetUsersUpdate { get; set; }
        public System.DateTime datetimeCreate { get; set; }
        public System.DateTime dateTimeUpdate { get; set; }
        public string id_AspNetUsersIdea { get; set; }
        public string description { get; set; }
        public string histiryEdit { get; set; }
        public string id_CMKO_PeriodResult { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual CMKO_PeriodResult CMKO_PeriodResult { get; set; }
    }
}
