//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisFinalBonus
    {
        public int id { get; set; }
        public double mPlan { get; set; }
        public double mFact { get; set; }
        public double ePlan { get; set; }
        public double eFact { get; set; }
    }
}
