//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_SummaryResultToMonth
    {
        public int id { get; set; }
        public string id_CMKO_PeriodResult { get; set; }
        public string id_AspNetUsers { get; set; }
        public double coefManager { get; set; }
        public double coefError { get; set; }
        public double coefErrorG { get; set; }
        public double nh { get; set; }
        public double nhG { get; set; }
        public double ordersAccrue { get; set; }
        public double remainingBonusAccrue { get; set; }
        public double gAccrue { get; set; }
        public double managerAccrue { get; set; }
        public double teachAccrue { get; set; }
        public double optimizationAccrue { get; set; }
        public double timeUpAccrue { get; set; }
        public double qualityAccrue { get; set; }
        public double rate { get; set; }
        public double tax { get; set; }
        public double result { get; set; }
        public double resultToMonth { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CMKO_PeriodResult CMKO_PeriodResult { get; set; }
    }
}
