//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisFinalBonus
    {
        public int id { get; set; }
        public double mPlan { get; set; }
        public double mFact { get; set; }
        public double ePlan { get; set; }
        public double eFact { get; set; }
    }
}
