//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisWithheldToBonusFund
    {
        public int id { get; set; }
        public double reclamationMPlan { get; set; }
        public double reclamationEPlan { get; set; }
        public double reclamationMFact { get; set; }
        public double reclamationEFact { get; set; }
        public double reclamationMGPlan { get; set; }
        public double reclamationEGPlan { get; set; }
        public double reclamationMGFact { get; set; }
        public double reclamationEGFact { get; set; }
    }
}
