//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_PeriodResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMKO_PeriodResult()
        {
            this.CMKO_Optimization = new HashSet<CMKO_Optimization>();
            this.CMKO_Teach = new HashSet<CMKO_Teach>();
            this.CMKO_ThisCoefManager = new HashSet<CMKO_ThisCoefManager>();
            this.CMKO_SummaryResultToMonth = new HashSet<CMKO_SummaryResultToMonth>();
        }
    
        public string period { get; set; }
        public bool close { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMKO_Optimization> CMKO_Optimization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMKO_Teach> CMKO_Teach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMKO_ThisCoefManager> CMKO_ThisCoefManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMKO_SummaryResultToMonth> CMKO_SummaryResultToMonth { get; set; }
    }
}
