//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisIndicatorsUsers
    {
        public int id { get; set; }
        public string id_AspNetUsers { get; set; }
        public double optimization { get; set; }
        public double speed1 { get; set; }
        public double speed2 { get; set; }
        public double speed3 { get; set; }
        public double teach { get; set; }
        public double rate1 { get; set; }
        public double rate2 { get; set; }
        public double rate3 { get; set; }
        public double tax1 { get; set; }
        public double tax2 { get; set; }
        public double tax3 { get; set; }
        public double coefError { get; set; }
        public double coefErrorG { get; set; }
        public double qualityBonus { get; set; }
        public double nhPlan { get; set; }
        public double nhFact { get; set; }
        public double nhGPlan { get; set; }
        public double nhGFact { get; set; }
        public double coefManager { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
