//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisAccrued
    {
        public int id { get; set; }
        public string id_AspNetUsers { get; set; }
        public double accruedPlan { get; set; }
        public double accruedFact { get; set; }
        public double withheldPlan { get; set; }
        public double withheldFact { get; set; }
        public double accruedTotalPlan { get; set; }
        public double accruedTotalFact { get; set; }
        public double bonusPlan { get; set; }
        public double bonusFact { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
