//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_CounterError
    {
        public int id { get; set; }
        public int fromM { get; set; }
        public int toM { get; set; }
        public int counter { get; set; }
        public int fromO { get; set; }
        public int toO { get; set; }
    }
}
