//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisWithheldToBonusFund
    {
        public int id { get; set; }
        public double reclamationMPlan { get; set; }
        public double reclamationEPlan { get; set; }
        public double reclamationMFact { get; set; }
        public double reclamationEFact { get; set; }
        public double reclamationMGPlan { get; set; }
        public double reclamationEGPlan { get; set; }
        public double reclamationMGFact { get; set; }
        public double reclamationEGFact { get; set; }
    }
}
