//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_CounterError
    {
        public int id { get; set; }
        public int fromM { get; set; }
        public int toM { get; set; }
        public int counter { get; set; }
        public int fromO { get; set; }
        public int toO { get; set; }
    }
}
