//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMKO_ThisDeductionsBonusFund
    {
        public int id { get; set; }
        public double deductionsMKOMPlan { get; set; }
        public double deductionsMKOMFact { get; set; }
        public double deductionsMKOEPlan { get; set; }
        public double deductionsMKOEFact { get; set; }
        public double deductionsMMPlan { get; set; }
        public double deductionsMMFact { get; set; }
        public double deductionsMEPlan { get; set; }
        public double deductionsMEFact { get; set; }
        public double deductionsGMPlan { get; set; }
        public double deductionsGMFact { get; set; }
        public double deductionsGEPlan { get; set; }
        public double deductionsGEFact { get; set; }
        public double balanceBonusFundMPlan { get; set; }
        public double balanceBonusFundMFact { get; set; }
        public double balanceBonusFundEPlan { get; set; }
        public double balanceBonusFundEFact { get; set; }
    }
}
