//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_FileOrder
    {
        public int id { get; set; }
        public int id_CMO_Order { get; set; }
        public string filname { get; set; }
    
        public virtual CMO_Order CMO_Order { get; set; }
    }
}
