//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_PositionPreOrder
    {
        public int id { get; set; }
        public int id_CMO_PreOrder { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public int id_CMO_TypeProduct { get; set; }
        public string folder { get; set; }
    
        public virtual CMO_PreOrder CMO_PreOrder { get; set; }
        public virtual CMO_TypeProduct CMO_TypeProduct { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
