//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMO_Tender()
        {
            this.CMO_UploadResult = new HashSet<CMO_UploadResult>();
        }
    
        public int id { get; set; }
        public int id_CMO_Order { get; set; }
        public int id_CMO_TypeTask { get; set; }
        public System.DateTime finishPlanClose { get; set; }
        public bool close { get; set; }
        public Nullable<System.DateTime> closeDateTime { get; set; }
        public string userClose { get; set; }
    
        public virtual CMO_Order CMO_Order { get; set; }
        public virtual CMO_TypeTask CMO_TypeTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMO_UploadResult> CMO_UploadResult { get; set; }
    }
}
