//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_CompanyMailList
    {
        public int id { get; set; }
        public int id_CMO_Company { get; set; }
        public string email { get; set; }
        public bool active { get; set; }
    
        public virtual CMO_Company CMO_Company { get; set; }
    }
}
