//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMO_UploadResult
    {
        public int id { get; set; }
        public int id_CMO_Tender { get; set; }
        public Nullable<System.DateTime> dateTimeUpload { get; set; }
        public string userUpload { get; set; }
        public double cost { get; set; }
        public Nullable<System.DateTime> dateComplited { get; set; }
        public int id_CMO_Company { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<bool> winnerBit { get; set; }
    
        public virtual CMO_Company CMO_Company { get; set; }
        public virtual CMO_Tender CMO_Tender { get; set; }
    }
}
