//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMOSRate
    {
        public int id { get; set; }
        public System.DateTime dateStart { get; set; }
        public Nullable<System.DateTime> dateFinish { get; set; }
        public double cost { get; set; }
    }
}
