//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMOSPositionPreOrder
    {
        public int id { get; set; }
        public int CMOSPreOrderId { get; set; }
        public string positionNum { get; set; }
        public string designation { get; set; }
        public string name { get; set; }
        public string index { get; set; }
        public double weight { get; set; }
        public double quantity { get; set; }
        public double summaryWeight { get; set; }
        public string color { get; set; }
        public string coating { get; set; }
        public string note { get; set; }
        public double quantity8 { get; set; }
        public double flow { get; set; }
        public Nullable<int> sku { get; set; }
    
        public virtual CMOSPreOrder CMOSPreOrder { get; set; }
    }
}
