//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentAttribute
    {
        public string ID { get; set; }
        public string ENTRY { get; set; }
        public string VERSION { get; set; }
        public int BundleID { get; set; }
        public int NODENO { get; set; }
        public int Flags { get; set; }
        public string AttributeName { get; set; }
        public int Copy { get; set; }
        public string AttributeValue { get; set; }
    }
}
