//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentData
    {
        public string ID { get; set; }
        public string ENTRY { get; set; }
        public string VERSION { get; set; }
        public string DeviceLetterCode { get; set; }
        public string Class { get; set; }
        public Nullable<int> ENTRYTYP { get; set; }
        public string Description { get; set; }
        public string LPNTR { get; set; }
        public string VSTATUS { get; set; }
        public string VersionText { get; set; }
        public Nullable<System.DateTime> DATEMAIN { get; set; }
        public Nullable<System.DateTime> LASTUPDT { get; set; }
        public string MPNTR { get; set; }
        public Nullable<int> Flags { get; set; }
        public string ArticleNumber { get; set; }
        public string Supplier { get; set; }
        public string SPNTR { get; set; }
        public string Class_main { get; set; }
        public string katek_1C { get; set; }
        public string katek_type_rkd { get; set; }
        public string katek_name_rkd { get; set; }
    }
}
