//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardRateToDateShipThisYear
    {
        public int C__заказа__Реестр_заказов_ { get; set; }
        public string quart { get; set; }
        public string Месяц { get; set; }
        public Nullable<double> RUR { get; set; }
        public Nullable<double> USD { get; set; }
        public string Валюта { get; set; }
        public int id { get; set; }
    }
}
