//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPManufacturingPower
    {
        public int id { get; set; }
        public int id_Devision { get; set; }
        public int workers { get; set; }
        public int planWork { get; set; }
        public double otherWorkCoef { get; set; }
        public double remarksCoef { get; set; }
        public int workDay { get; set; }
        public double modeWorking { get; set; }
        public int workersBeforeMoves { get; set; }
        public double modeWorkingBeforeMoves { get; set; }
    
        public virtual Devision Devision { get; set; }
    }
}
