//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKOKBHss
    {
        public string Quart { get; set; }
        public double KBM { get; set; }
        public double KBE { get; set; }
        public int id { get; set; }
        public double KBMR { get; set; }
        public double KBER { get; set; }
    }
}
