//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKO_Quartal
    {
        public double NormHoure { get; set; }
        public string User { get; set; }
        public string DevisionName { get; set; }
        public int id { get; set; }
        public int month { get; set; }
    }
}
