//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKO_UsersMonthPlan
    {
        public int id { get; set; }
        public string id_AspNetUsers { get; set; }
        public int id_ProductionCalendar { get; set; }
        public double k { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ProductionCalendar ProductionCalendar { get; set; }
    }
}
