//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPComments
    {
        public System.Guid taskUID { get; set; }
        public int orderNumber { get; set; }
        public string taskName { get; set; }
        public string workerName { get; set; }
        public int counterState1 { get; set; }
        public int counterState2 { get; set; }
        public string notes { get; set; }
        public int id { get; set; }
    }
}
