//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTV_BasicPlanData
    {
        public int inThisDay { get; set; }
        public int inThisDayPercent { get; set; }
        public int inThisMonth { get; set; }
        public int inThisMonthPercent { get; set; }
        public double factWork { get; set; }
        public int workDay { get; set; }
    }
}
