//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardKOMP2
    {
        public string period { get; set; }
        public string ciliricalName { get; set; }
        public string devisionName { get; set; }
        public double k { get; set; }
        public double plan { get; set; }
        public double plan10 { get; set; }
        public double plan20 { get; set; }
        public double plan30 { get; set; }
        public double normHoure { get; set; }
        public double normHoureFact { get; set; }
        public int id { get; set; }
    }
}
