//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPComments
    {
        public System.Guid taskUID { get; set; }
        public int orderNumber { get; set; }
        public string taskName { get; set; }
        public string workerName { get; set; }
        public int counterState1 { get; set; }
        public int counterState2 { get; set; }
        public string notes { get; set; }
        public int id { get; set; }
    }
}
