//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPDevisionCoef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardBPDevisionCoef()
        {
            this.DashboardBPManpowerManuf = new HashSet<DashboardBPManpowerManuf>();
        }
    
        public int id { get; set; }
        public int id_Devision { get; set; }
        public double coefDefaultWork { get; set; }
        public double coefRemarks { get; set; }
    
        public virtual Devision Devision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBPManpowerManuf> DashboardBPManpowerManuf { get; set; }
    }
}
