//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_ProjectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardBP_ProjectList()
        {
            this.DashboardBP_ProjectTasks = new HashSet<DashboardBP_ProjectTasks>();
        }
    
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public int id_DashboardBP_State { get; set; }
        public System.DateTime contractDate { get; set; }
        public System.DateTime planDateComplited { get; set; }
        public System.DateTime planDateStart { get; set; }
        public int planDuration { get; set; }
        public int planProjectPercentCompleted { get; set; }
    
        public virtual DashboardBP_State DashboardBP_State { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBP_ProjectTasks> DashboardBP_ProjectTasks { get; set; }
    }
}
