//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardDN
    {
        public int id { get; set; }
        public string month { get; set; }
        public int profit { get; set; }
        public int rate { get; set; }
        public double sn { get; set; }
        public double svn { get; set; }
        public bool filtr { get; set; }
    }
}
