//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPManpowerManuf
    {
        public int id { get; set; }
        public int id_DashboardBPDevisionCoef { get; set; }
        public double manpowerPrj { get; set; }
        public double planWork { get; set; }
        public int workday { get; set; }
        public double workMode { get; set; }
        public double manpowerResult { get; set; }
        public double workModeResult { get; set; }
        public int id_ProductionCalendar { get; set; }
    
        public virtual DashboardBPDevisionCoef DashboardBPDevisionCoef { get; set; }
    }
}
