//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPManpowerManuf
    {
        public int id { get; set; }
        public int id_DashboardBPDevisionCoef { get; set; }
        public double manpowerPrj { get; set; }
        public double planWork { get; set; }
        public int workday { get; set; }
        public double workMode { get; set; }
        public double manpowerResult { get; set; }
        public double workModeResult { get; set; }
        public int id_ProductionCalendar { get; set; }
    
        public virtual DashboardBPDevisionCoef DashboardBPDevisionCoef { get; set; }
        public virtual ProductionCalendar ProductionCalendar { get; set; }
    }
}
