//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_HSSPOSmall
    {
        public int id { get; set; }
        public int id_DashboardBP_State { get; set; }
        public int year { get; set; }
        public int numberMonth { get; set; }
        public int data { get; set; }
        public string yearMonth { get; set; }
    }
}
