//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_ProjectTasks
    {
        public int id { get; set; }
        public Nullable<double> basicDuration { get; set; }
        public Nullable<System.DateTime> basicStart { get; set; }
        public Nullable<System.DateTime> basicFinish { get; set; }
        public Nullable<double> basicWork { get; set; }
        public double duration { get; set; }
        public double remainingDuration { get; set; }
        public double factDuration { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime finish { get; set; }
        public double work { get; set; }
        public double remainingWork { get; set; }
        public double factWork { get; set; }
        public double percentWorkComplited { get; set; }
        public double percentComplited { get; set; }
        public double percentPhisicalComplited { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public bool isCritical { get; set; }
        public int priority { get; set; }
        public Nullable<double> NK { get; set; }
        public Nullable<int> id_WBS { get; set; }
        public int id_DashboardBP_ProjectList { get; set; }
        public System.Guid taskUID { get; set; }
        public string id_AspNetUsers { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DashboardBP_ProjectList DashboardBP_ProjectList { get; set; }
        public virtual WBS WBS { get; set; }
    }
}
