//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBP_ProjectList
    {
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public int id_DashboardBP_State { get; set; }
        public System.DateTime contractDate { get; set; }
        public System.DateTime planDateComplited { get; set; }
        public System.DateTime planDateStart { get; set; }
        public int planDuration { get; set; }
        public int planProjectPercentCompleted { get; set; }
    
        public virtual DashboardBP_State DashboardBP_State { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
