//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBPDevisionCoef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardBPDevisionCoef()
        {
            this.DashboardBPManpowerManuf = new HashSet<DashboardBPManpowerManuf>();
        }
    
        public int id { get; set; }
        public int id_Devision { get; set; }
        public double coefDefaultWork { get; set; }
        public double coefRemarks { get; set; }
    
        public virtual Devision Devision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardBPManpowerManuf> DashboardBPManpowerManuf { get; set; }
    }
}
