//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTV_BasicPlanData
    {
        public int inThisDay { get; set; }
        public int inThisDayPercent { get; set; }
        public int inThisMonth { get; set; }
        public int inThisMonthPercent { get; set; }
        public double factWork { get; set; }
        public int workDay { get; set; }
    }
}
