//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardCountPZInDevision
    {
        public string C_нед { get; set; }
        public string C__заказа { get; set; }
        public string СП { get; set; }
        public int k { get; set; }
        public int id { get; set; }
    }
}
