//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardDH
    {
        public int id { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int Rate { get; set; }
        public int SSM { get; set; }
        public int SSW { get; set; }
        public int IK { get; set; }
        public int PK { get; set; }
        public int PI { get; set; }
        public int Profit { get; set; }
    }
}
