//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTV_DataForProjectPortfolio
    {
        public int id { get; set; }
        public string orderNumber { get; set; }
        public int tcpm { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
        public System.DateTime dataOtgruzkiBP { get; set; }
        public int remainingDuration { get; set; }
        public int duration { get; set; }
        public int percentComplited { get; set; }
    }
}
