//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_Name
    {
        public int id { get; set; }
        public int id_Debit_WorkBit { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public string nameRKD { get; set; }
        public string nameTableModul { get; set; }
        public string name1c { get; set; }
    
        public virtual Debit_WorkBit Debit_WorkBit { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
