//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitReclamation
    {
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public System.DateTime dateOpen { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
