//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_EmailList
    {
        public int id { get; set; }
        public string email { get; set; }
        public bool C1 { get; set; }
        public bool C2 { get; set; }
        public bool C3 { get; set; }
        public bool C4 { get; set; }
        public bool C5 { get; set; }
        public bool C6 { get; set; }
        public bool C7 { get; set; }
        public bool C8 { get; set; }
        public bool C9 { get; set; }
        public bool C10 { get; set; }
        public bool C11 { get; set; }
        public bool C12 { get; set; }
        public bool C13 { get; set; }
        public bool C14 { get; set; }
        public bool C15 { get; set; }
        public bool C18 { get; set; }
        public bool C21 { get; set; }
        public bool C22 { get; set; }
        public bool C25 { get; set; }
        public bool C26 { get; set; }
    }
}
