//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_CMR
    {
        public int id { get; set; }
        public int id_DebitTask { get; set; }
        public System.DateTime dateShip { get; set; }
        public string number { get; set; }
    
        public virtual Debit_WorkBit Debit_WorkBit { get; set; }
    }
}
