//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_Platform
    {
        public int id { get; set; }
        public Nullable<int> id_PlanZakaz { get; set; }
        public Nullable<int> massa { get; set; }
        public Nullable<int> countPlatform { get; set; }
        public string numPlatform { get; set; }
        public string numPlomb { get; set; }
        public string gabar { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
