//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drill
    {
        public int EntryID { get; set; }
        public Nullable<float> Diameter { get; set; }
        public Nullable<float> Tolerance { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Type { get; set; }
        public byte[] TData { get; set; }
    }
}
