//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalKATEKEntities : DbContext
    {
        public PortalKATEKEntities()
            : base("name=PortalKATEKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<DashboardKO_Quartal> DashboardKO_Quartal { get; set; }
        public virtual DbSet<Debit_EmailList> Debit_EmailList { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<FolderDocument> FolderDocument { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Project_WBSLevelStruct> Project_WBSLevelStruct { get; set; }
        public virtual DbSet<ProjectServer_CreateTasks> ProjectServer_CreateTasks { get; set; }
        public virtual DbSet<ProjectServer_UpdateTasks> ProjectServer_UpdateTasks { get; set; }
        public virtual DbSet<ProjectWBS> ProjectWBS { get; set; }
        public virtual DbSet<RKD_FailBPlan> RKD_FailBPlan { get; set; }
        public virtual DbSet<RKD_HistoryTaskVersion> RKD_HistoryTaskVersion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tmpRecl> tmpRecl { get; set; }
        public virtual DbSet<UserPO> UserPO { get; set; }
        public virtual DbSet<WBS_ClassicStruct> WBS_ClassicStruct { get; set; }
        public virtual DbSet<XTEO> XTEO { get; set; }
        public virtual DbSet<CMO_Report> CMO_Report { get; set; }
        public virtual DbSet<RKD_TaskUIDProjectUD> RKD_TaskUIDProjectUD { get; set; }
        public virtual DbSet<VV_infPost> VV_infPost { get; set; }
        public virtual DbSet<OTKMultiSelectList> OTKMultiSelectList { get; set; }
        public virtual DbSet<PWA_EmpProject> PWA_EmpProject { get; set; }
        public virtual DbSet<Reclamation_Order> Reclamation_Order { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CMO_Company> CMO_Company { get; set; }
        public virtual DbSet<CMO_CompanyMailList> CMO_CompanyMailList { get; set; }
        public virtual DbSet<CMO_FileOrder> CMO_FileOrder { get; set; }
        public virtual DbSet<CMO_HoureTender> CMO_HoureTender { get; set; }
        public virtual DbSet<CMO_Mail> CMO_Mail { get; set; }
        public virtual DbSet<CMO_Order> CMO_Order { get; set; }
        public virtual DbSet<CMO_PositionOrder> CMO_PositionOrder { get; set; }
        public virtual DbSet<CMO_PositionPreOrder> CMO_PositionPreOrder { get; set; }
        public virtual DbSet<CMO_PreOrder> CMO_PreOrder { get; set; }
        public virtual DbSet<CMO_Tender> CMO_Tender { get; set; }
        public virtual DbSet<CMO_TypeProduct> CMO_TypeProduct { get; set; }
        public virtual DbSet<CMO_TypeTask> CMO_TypeTask { get; set; }
        public virtual DbSet<CMO_UploadResult> CMO_UploadResult { get; set; }
        public virtual DbSet<Debit_CMR> Debit_CMR { get; set; }
        public virtual DbSet<Debit_CostUpdate> Debit_CostUpdate { get; set; }
        public virtual DbSet<Debit_DataReportOprih> Debit_DataReportOprih { get; set; }
        public virtual DbSet<Debit_IstPost> Debit_IstPost { get; set; }
        public virtual DbSet<Debit_MatchingType> Debit_MatchingType { get; set; }
        public virtual DbSet<Debit_Name> Debit_Name { get; set; }
        public virtual DbSet<Debit_PeriodReportOprih> Debit_PeriodReportOprih { get; set; }
        public virtual DbSet<Debit_Platform> Debit_Platform { get; set; }
        public virtual DbSet<Debit_TN> Debit_TN { get; set; }
        public virtual DbSet<Debit_WorkBit> Debit_WorkBit { get; set; }
        public virtual DbSet<Devision> Devision { get; set; }
        public virtual DbSet<OTK_ChaeckList> OTK_ChaeckList { get; set; }
        public virtual DbSet<OTK_CounterErrorKO> OTK_CounterErrorKO { get; set; }
        public virtual DbSet<OTK_Reclamation> OTK_Reclamation { get; set; }
        public virtual DbSet<OTK_ReclamationAnswer> OTK_ReclamationAnswer { get; set; }
        public virtual DbSet<OTK_ReclamationKO> OTK_ReclamationKO { get; set; }
        public virtual DbSet<OTK_ReclamationKO_DocData> OTK_ReclamationKO_DocData { get; set; }
        public virtual DbSet<OTK_ReclamationKO_DocDataOTK> OTK_ReclamationKO_DocDataOTK { get; set; }
        public virtual DbSet<OTK_ReclamationKO_DocResult> OTK_ReclamationKO_DocResult { get; set; }
        public virtual DbSet<OTK_ReclamationKO_DocResultOTK> OTK_ReclamationKO_DocResultOTK { get; set; }
        public virtual DbSet<OTK_TypeReclamation> OTK_TypeReclamation { get; set; }
        public virtual DbSet<PostAlertShip> PostAlertShip { get; set; }
        public virtual DbSet<PostMatching> PostMatching { get; set; }
        public virtual DbSet<PZ_Client> PZ_Client { get; set; }
        public virtual DbSet<PZ_Currency> PZ_Currency { get; set; }
        public virtual DbSet<PZ_Dostavka> PZ_Dostavka { get; set; }
        public virtual DbSet<PZ_FIO> PZ_FIO { get; set; }
        public virtual DbSet<PZ_OperatorDogovora> PZ_OperatorDogovora { get; set; }
        public virtual DbSet<PZ_PlanZakaz> PZ_PlanZakaz { get; set; }
        public virtual DbSet<PZ_ProductType> PZ_ProductType { get; set; }
        public virtual DbSet<PZ_Setup> PZ_Setup { get; set; }
        public virtual DbSet<PZ_TEO> PZ_TEO { get; set; }
        public virtual DbSet<PZ_TypeShip> PZ_TypeShip { get; set; }
        public virtual DbSet<RKD_Despatching> RKD_Despatching { get; set; }
        public virtual DbSet<RKD_FileMailVersion> RKD_FileMailVersion { get; set; }
        public virtual DbSet<RKD_GIP> RKD_GIP { get; set; }
        public virtual DbSet<RKD_Institute> RKD_Institute { get; set; }
        public virtual DbSet<RKD_Mail_TimeForComplited> RKD_Mail_TimeForComplited { get; set; }
        public virtual DbSet<RKD_Mail_Version> RKD_Mail_Version { get; set; }
        public virtual DbSet<RKD_Order> RKD_Order { get; set; }
        public virtual DbSet<RKD_PostList> RKD_PostList { get; set; }
        public virtual DbSet<RKD_Question> RKD_Question { get; set; }
        public virtual DbSet<RKD_QuestionData> RKD_QuestionData { get; set; }
        public virtual DbSet<RKD_Task> RKD_Task { get; set; }
        public virtual DbSet<RKD_TaskVersion> RKD_TaskVersion { get; set; }
        public virtual DbSet<RKD_TypeTask> RKD_TypeTask { get; set; }
        public virtual DbSet<RKD_Version> RKD_Version { get; set; }
        public virtual DbSet<RKD_VersionDay> RKD_VersionDay { get; set; }
        public virtual DbSet<RKD_VersionWork> RKD_VersionWork { get; set; }
        public virtual DbSet<Service_Reclamation> Service_Reclamation { get; set; }
        public virtual DbSet<Service_ReclamationAddOrder> Service_ReclamationAddOrder { get; set; }
        public virtual DbSet<Service_ReclamationAnswerDevision> Service_ReclamationAnswerDevision { get; set; }
        public virtual DbSet<Service_ReclamationCorrespondence> Service_ReclamationCorrespondence { get; set; }
        public virtual DbSet<Service_ReclamationCounterError> Service_ReclamationCounterError { get; set; }
        public virtual DbSet<Service_ReclamationInfo> Service_ReclamationInfo { get; set; }
        public virtual DbSet<Service_ReclamationMonthDoc> Service_ReclamationMonthDoc { get; set; }
        public virtual DbSet<Service_ReclamationMonthResult> Service_ReclamationMonthResult { get; set; }
        public virtual DbSet<Service_ReclamationPZ> Service_ReclamationPZ { get; set; }
        public virtual DbSet<Service_ReclamationType> Service_ReclamationType { get; set; }
        public virtual DbSet<Service_ReclamationWhoAdd> Service_ReclamationWhoAdd { get; set; }
        public virtual DbSet<Service_TypeCorrespondence> Service_TypeCorrespondence { get; set; }
        public virtual DbSet<Service_TypeReclamation> Service_TypeReclamation { get; set; }
        public virtual DbSet<Service_TypeReclamationDocument> Service_TypeReclamationDocument { get; set; }
        public virtual DbSet<TaskForPZ> TaskForPZ { get; set; }
        public virtual DbSet<TypeRKD_Mail_Version> TypeRKD_Mail_Version { get; set; }
        public virtual DbSet<TypeTaskForPZ> TypeTaskForPZ { get; set; }
        public virtual DbSet<VV_Position> VV_Position { get; set; }
        public virtual DbSet<VVPZ> VVPZ { get; set; }
    }
}
