//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCostsER
    {
        public string Период { get; set; }
        public Nullable<int> Коммерческие_издержки { get; set; }
        public Nullable<int> Издержки__ЗП_ПО_ { get; set; }
        public Nullable<int> Издержки___по_кредиту { get; set; }
        public Nullable<int> Постоянные_издержки { get; set; }
        public Nullable<int> Фактическая_С_С_материалов { get; set; }
        public Nullable<int> Трудозатраты_ПО__по_заказам_ { get; set; }
        public Nullable<int> Коммерческие_издержки_Ш { get; set; }
        public Nullable<int> Коммерческие_издержки_прочие { get; set; }
        public Nullable<int> Условно_ПИ { get; set; }
        public int id { get; set; }
    }
}
