//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinCostsClient
    {
        public Nullable<int> year { get; set; }
        public int C__заказа__Реестр_заказов_ { get; set; }
        public Nullable<double> Выручка_без_НДС { get; set; }
        public Nullable<double> С_С_материалов { get; set; }
        public Nullable<double> С_С_зп_рабочих { get; set; }
        public Nullable<double> Издержки_коммерческие { get; set; }
        public Nullable<double> C__по_кредиту { get; set; }
        public Nullable<double> Постоянные_издержки { get; set; }
        public Nullable<double> НОП { get; set; }
        public Nullable<double> Фактический_С_С { get; set; }
        public string Заказчик__группа_ { get; set; }
        public int id { get; set; }
    }
}
