//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinPercentSredniyVzveshenniyNOP
    {
        public string Заказчик__группа_ { get; set; }
        public Nullable<double> Средний_взвешеный_НОП { get; set; }
        public int id { get; set; }
    }
}
