//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTION_ATTRIBUTES
    {
        public string NAME { get; set; }
        public int ID { get; set; }
        public int PORT_NUMBER { get; set; }
        public string ATTRIBUTE_NAME { get; set; }
        public int COPY { get; set; }
        public string STATE_ID { get; set; }
        public string ATTRIBUTE_VALUE { get; set; }
    }
}
