//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONAL_UNITS
    {
        public string NAME { get; set; }
        public int ID { get; set; }
        public string SYMBOL { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
