//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONAL_UNIT_STATES
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string FU_NAME { get; set; }
        public int FU_ID { get; set; }
        public Nullable<int> ORDER_NUM { get; set; }
        public Nullable<int> FLAGS { get; set; }
    }
}
