//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatePinRelation
    {
        public string ENTRY { get; set; }
        public int GateNumber { get; set; }
        public int PinNumber { get; set; }
        public int Representation { get; set; }
        public int NodeNumber { get; set; }
    }
}
