//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Illiquid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Illiquid()
        {
            this.IlliquidNote = new HashSet<IlliquidNote>();
        }
    
        public int Id { get; set; }
        public int IlliquidStockStateId { get; set; }
        public int IlliquidTypeId { get; set; }
        public string UserId { get; set; }
        public int IlliquidSourceTypeId { get; set; }
        public int DevisionId { get; set; }
        public string Note { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Devision Devision { get; set; }
        public virtual IlliquidSourceType IlliquidSourceType { get; set; }
        public virtual IlliquidStockState IlliquidStockState { get; set; }
        public virtual IlliquidType IlliquidType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidNote> IlliquidNote { get; set; }
    }
}
