//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidGroupAction
    {
        public int Id { get; set; }
        public int IlliquidId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsPeriod { get; set; }
        public float Change { get; set; }
        public float SN { get; set; }
        public float Ordered { get; set; }
        public float Added { get; set; }
        public float AddedX { get; set; }
        public float Replacement { get; set; }
        public float LastMoveStock { get; set; }
        public float State { get; set; }
    
        public virtual Illiquid Illiquid { get; set; }
    }
}
