//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidAction
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public System.DateTime Date { get; set; }
        public float Quentity { get; set; }
        public int IlliquidId { get; set; }
        public string Note { get; set; }
    
        public virtual Illiquid Illiquid { get; set; }
        public virtual IlliquidTypeAction IlliquidTypeAction { get; set; }
    }
}
