//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidChangeInTheNorm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlliquidChangeInTheNorm()
        {
            this.IlliquidChangeInTheNormUsers = new HashSet<IlliquidChangeInTheNormUsers>();
        }
    
        public int Id { get; set; }
        public int PlanOrderId { get; set; }
        public int SKUId { get; set; }
        public float ChangeInTheNorm { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        public virtual SKU SKU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidChangeInTheNormUsers> IlliquidChangeInTheNormUsers { get; set; }
    }
}
