//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Illiquid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Illiquid()
        {
            this.IlliquidAction = new HashSet<IlliquidAction>();
            this.IlliquidGroupAction = new HashSet<IlliquidGroupAction>();
        }
    
        public int id { get; set; }
        public Nullable<int> idIlliquidStockStateBefore { get; set; }
        public int idIlliquidStockStateNext { get; set; }
        public float quantityBefore { get; set; }
        public float quantityNext { get; set; }
        public bool IsAnalisis { get; set; }
        public Nullable<int> DevisionAutomatic { get; set; }
        public Nullable<int> DevisionCorrect { get; set; }
        public string Note { get; set; }
        public string Cause { get; set; }
    
        public virtual Devision Devision { get; set; }
        public virtual Devision Devision1 { get; set; }
        public virtual IlliquidStockState IlliquidStockState { get; set; }
        public virtual IlliquidStockState IlliquidStockState1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidAction> IlliquidAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidGroupAction> IlliquidGroupAction { get; set; }
    }
}
