//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidNote
    {
        public int Id { get; set; }
        public int IlliquidId { get; set; }
        public System.DateTime Create { get; set; }
        public string UserId { get; set; }
        public string UserIlliquidId { get; set; }
        public int IlliquidTypeId { get; set; }
        public int IlliquidSourceTypeId { get; set; }
        public string Note { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Illiquid Illiquid { get; set; }
        public virtual IlliquidSourceType IlliquidSourceType { get; set; }
        public virtual IlliquidType IlliquidType { get; set; }
    }
}
