//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidNorm
    {
        public int Id { get; set; }
        public int SKUId { get; set; }
        public int PlanOrderId { get; set; }
        public float Quentity { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        public virtual SKU SKU { get; set; }
    }
}
