//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidStockState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlliquidStockState()
        {
            this.Illiquid = new HashSet<Illiquid>();
            this.Illiquid1 = new HashSet<Illiquid>();
        }
    
        public int Id { get; set; }
        public int SKUId { get; set; }
        public System.DateTime Date { get; set; }
        public float IlliquidQue { get; set; }
        public float IlliquidSum { get; set; }
        public float SurplusQue { get; set; }
        public float SurplusSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Illiquid> Illiquid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Illiquid> Illiquid1 { get; set; }
        public virtual SKU SKU { get; set; }
    }
}
