//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlliquidReplacement
    {
        public int Id { get; set; }
        public int SKUNormId { get; set; }
        public int SKUIssuedId { get; set; }
        public int PlanOrderId { get; set; }
        public float QuentityNorm { get; set; }
        public float QuentityIssue { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        public virtual SKU SKU { get; set; }
        public virtual SKU SKU1 { get; set; }
    }
}
