//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManpowerPO
    {
        public System.DateTime dateTimeReport { get; set; }
        public Nullable<System.DateTime> TimeByDay { get; set; }
        public string Неделя { get; set; }
        public string СДРес { get; set; }
        public Nullable<int> AssignmentWork { get; set; }
        public Nullable<int> WorkDay { get; set; }
        public int id { get; set; }
    }
}
