//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelData
    {
        public string ID { get; set; }
        public string Entry { get; set; }
        public Nullable<int> Type { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LASTUPDT { get; set; }
        public Nullable<System.DateTime> DATEMAIN { get; set; }
    }
}
