//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOPOpenOrderLastTheerYears
    {
        public string Месяц { get; set; }
        public string год { get; set; }
        public Nullable<double> НОП { get; set; }
        public Nullable<double> Выручка { get; set; }
        public string quart { get; set; }
    }
}
