//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTables()
        {
            this.OrdersTablesPositions = new HashSet<OrdersTablesPositions>();
        }
    
        public int id { get; set; }
        public System.DateTime dateCreate { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public Nullable<System.DateTime> dateRemove { get; set; }
        public bool isActive { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTablesPositions> OrdersTablesPositions { get; set; }
    }
}
