//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTK_ReclamationAnswer
    {
        public int id { get; set; }
        public int ReclamationId { get; set; }
        public string Text { get; set; }
        public string User { get; set; }
        public int Devision { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string UserUpdate { get; set; }
        public string userError { get; set; }
        public Nullable<int> countError { get; set; }
        public Nullable<int> userPO { get; set; }
        public string descriptionManagerKO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Devision Devision1 { get; set; }
        public virtual OTK_CounterErrorKO OTK_CounterErrorKO { get; set; }
        public virtual OTK_Reclamation OTK_Reclamation { get; set; }
    }
}
