//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTK_ReclamationKO_DocResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OTK_ReclamationKO_DocResult()
        {
            this.OTK_ReclamationKO_DocData = new HashSet<OTK_ReclamationKO_DocData>();
        }
    
        public int id { get; set; }
        public System.DateTime datetimeCreate { get; set; }
        public string numberDoc { get; set; }
        public bool write { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTK_ReclamationKO_DocData> OTK_ReclamationKO_DocData { get; set; }
    }
}
