//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTK_Reclamation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OTK_Reclamation()
        {
            this.OTK_ReclamationAnswer = new HashSet<OTK_ReclamationAnswer>();
        }
    
        public int Id { get; set; }
        public int CheckList { get; set; }
        public int TypeReclamation { get; set; }
        public bool Complited { get; set; }
        public string ReclamationText { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public string User { get; set; }
        public double LaborCostManufacturing { get; set; }
        public double LaborCostOTK { get; set; }
        public string AnswerText { get; set; }
        public string AnswerUser { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public Nullable<int> Devision { get; set; }
        public Nullable<bool> mailPost { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Devision Devision1 { get; set; }
        public virtual OTK_ChaeckList OTK_ChaeckList { get; set; }
        public virtual OTK_TypeReclamation OTK_TypeReclamation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTK_ReclamationAnswer> OTK_ReclamationAnswer { get; set; }
    }
}
