//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTK_ReclamationKO_DocData
    {
        public int id { get; set; }
        public int id_OTK_ReclamationKO_DocResult { get; set; }
        public int id_ReclamationKO { get; set; }
        public int id_OTK_CounterErrorKO { get; set; }
    
        public virtual OTK_CounterErrorKO OTK_CounterErrorKO { get; set; }
        public virtual OTK_ReclamationKO OTK_ReclamationKO { get; set; }
        public virtual OTK_ReclamationKO_DocResult OTK_ReclamationKO_DocResult { get; set; }
    }
}
