//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTK_ReclamationKO
    {
        public int id { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public string userCreate { get; set; }
        public string userUpdate { get; set; }
        public int order { get; set; }
        public int typeReclamation { get; set; }
        public int countError { get; set; }
        public bool shippedOrder { get; set; }
        public bool clouseReclamation { get; set; }
        public string userError { get; set; }
        public string textReclamation { get; set; }
        public string textAnswer { get; set; }
        public Nullable<double> time { get; set; }
        public Nullable<bool> aplayResylt { get; set; }
        public string descriptionManagerKO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        public virtual OTK_CounterErrorKO OTK_CounterErrorKO { get; set; }
        public virtual OTK_TypeReclamation OTK_TypeReclamation { get; set; }
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
    }
}
