//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outlines
    {
        public string Entry { get; set; }
        public int OutlineNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> Z { get; set; }
        public Nullable<double> LineY { get; set; }
        public Nullable<double> LineZ { get; set; }
        public Nullable<double> AreaZ { get; set; }
        public Nullable<double> Height { get; set; }
        public byte[] OutlineData { get; set; }
        public Nullable<int> RestrictedLayer { get; set; }
        public Nullable<int> DescriptionLevel { get; set; }
        public Nullable<int> Flags { get; set; }
    }
}
