//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlineSymbols
    {
        public string Entry { get; set; }
        public int OutlineNumber { get; set; }
        public int ViewNumber { get; set; }
        public string Symbol { get; set; }
    }
}
