//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadStack
    {
        public int EntryID { get; set; }
        public string PadSym { get; set; }
        public int LayerID { get; set; }
        public Nullable<int> Flags { get; set; }
    }
}
