//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PercentSredniyVzveshenniyNOP
    {
        public int year { get; set; }
        public string quart { get; set; }
        public string Месяц { get; set; }
        public double Средний_взвешеный_НОП { get; set; }
        public int id { get; set; }
    }
}
