//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysPin
    {
        public string Entry { get; set; }
        public int PinNumber { get; set; }
        public Nullable<double> ConnX { get; set; }
        public Nullable<double> ConnY { get; set; }
        public Nullable<double> ConnZ { get; set; }
        public Nullable<int> ConnType { get; set; }
        public Nullable<int> ConnDirection { get; set; }
        public Nullable<int> WireColor { get; set; }
        public Nullable<float> ConnDimension1 { get; set; }
        public Nullable<float> ConnDimension2 { get; set; }
        public Nullable<float> AWGMin { get; set; }
        public Nullable<float> AWGMax { get; set; }
        public Nullable<float> ConnDimensionMax { get; set; }
        public Nullable<int> WireMax { get; set; }
        public Nullable<double> SpineX { get; set; }
        public Nullable<double> SpineY { get; set; }
        public Nullable<double> SpineZ { get; set; }
        public Nullable<double> SlopeAngle { get; set; }
        public Nullable<double> PluggableDepth { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<int> PinLayer { get; set; }
        public Nullable<double> PinRotation { get; set; }
        public Nullable<int> TestPointCode { get; set; }
        public string TechStackS { get; set; }
        public string TechStackC { get; set; }
        public Nullable<int> DrillID { get; set; }
        public Nullable<int> Flags2 { get; set; }
    }
}
