//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pin
    {
        public string ENTRY { get; set; }
        public int COPY { get; set; }
        public string PHYSPIN { get; set; }
        public Nullable<int> FUNCT { get; set; }
        public Nullable<int> PINEQUIV { get; set; }
        public Nullable<int> LPINEQV { get; set; }
        public string PINNAME { get; set; }
        public Nullable<int> NPINEQV { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> TPNPRIO { get; set; }
        public Nullable<int> FLAGS2 { get; set; }
    }
}
