//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFactCostsThisYear
    {
        public System.DateTime dateReport { get; set; }
        public string year { get; set; }
        public string Период { get; set; }
        public Nullable<int> ФКИ { get; set; }
        public Nullable<int> ФЗП { get; set; }
        public Nullable<int> ФППК { get; set; }
        public Nullable<int> ФПИ { get; set; }
        public Nullable<int> ФКИШ { get; set; }
        public Nullable<int> ФКИП { get; set; }
        public Nullable<int> ФУП { get; set; }
        public Nullable<double> ФХСС { get; set; }
        public Nullable<double> ПКИ { get; set; }
        public Nullable<double> ПХСС { get; set; }
        public Nullable<double> ПЗП { get; set; }
        public Nullable<double> ПППК { get; set; }
        public Nullable<double> ППИ { get; set; }
        public Nullable<double> ФИ { get; set; }
        public Nullable<double> ПИ { get; set; }
        public int id { get; set; }
    }
}
