//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOrders
    {
        public int id { get; set; }
        public int id_SpecificationsPositions { get; set; }
        public int id_Products { get; set; }
        public string description { get; set; }
        public string Gruzopoluchatel { get; set; }
        public string PostAdresGruzopoluchatel { get; set; }
        public string INNGruzopoluchatel { get; set; }
        public string OKPOGruzopoluchatelya { get; set; }
        public byte[] KodGruzopoluchatela { get; set; }
        public string StantionGruzopoluchatel { get; set; }
        public string KodStanciiGruzopoluchatelya { get; set; }
        public string OsobieOtmetkiGruzopoluchatelya { get; set; }
        public string DescriptionGruzopoluchatel { get; set; }
        public int id_PZ_Dostavka { get; set; }
        public System.Guid projectUID { get; set; }
        public bool remove { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public int id_AdvancePaynemts { get; set; }
    
        public virtual AdvancePaynemts AdvancePaynemts { get; set; }
        public virtual Products Products { get; set; }
        public virtual SpecificationsPositions SpecificationsPositions { get; set; }
    }
}
