//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVerificationItemsLog
    {
        public int id { get; set; }
        public int id_PlanVerificationItems { get; set; }
        public string id_AspNetUsers { get; set; }
        public System.DateTime date { get; set; }
        public string action { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PlanVerificationItems PlanVerificationItems { get; set; }
    }
}
