//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFactCosts
    {
        public Nullable<int> year { get; set; }
        public string Период { get; set; }
        public Nullable<int> Коммерческие_издержки { get; set; }
        public Nullable<int> Издержки__ЗП_ПО_ { get; set; }
        public Nullable<int> Издержки___по_кредиту { get; set; }
        public Nullable<int> Постоянные_издержки { get; set; }
        public Nullable<int> Коммерческие_издержки_Ш { get; set; }
        public Nullable<int> Коммерческие_издержки_прочие { get; set; }
        public Nullable<int> Условно_ПИ { get; set; }
        public Nullable<double> ХИК { get; set; }
        public Nullable<double> ХСС { get; set; }
        public Nullable<double> ХССЗП { get; set; }
        public Nullable<double> ХППК { get; set; }
        public Nullable<double> ХПИ { get; set; }
        public Nullable<decimal> Тр_ты_ПО { get; set; }
        public Nullable<double> ХССФакт { get; set; }
        public Nullable<double> ОтклЗППО { get; set; }
        public Nullable<double> ОтклППК { get; set; }
        public Nullable<double> ОтклПИ { get; set; }
        public Nullable<double> ОтклКИ { get; set; }
        public Nullable<double> ОтклСС { get; set; }
        public Nullable<double> Плановые_издержки { get; set; }
        public Nullable<double> Фактические_издержки { get; set; }
        public Nullable<double> Откл_издержек { get; set; }
        public int id { get; set; }
        public Nullable<int> комиссия_от_выручки { get; set; }
        public Nullable<int> претензии { get; set; }
    }
}
