//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlugInfo
    {
        public string ENTRY { get; set; }
        public string VERSION { get; set; }
        public int COPY { get; set; }
        public string PINCOMP { get; set; }
        public Nullable<bool> ActiveCounterPart { get; set; }
        public string PINPART { get; set; }
        public Nullable<bool> ActiveFittingPart { get; set; }
        public Nullable<int> PinNumber { get; set; }
        public Nullable<bool> ActiveWireSeal { get; set; }
    }
}
