//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public System.DateTime id { get; set; }
        public System.DateTime date { get; set; }
        public string num { get; set; }
        public System.DateTime dateCreate { get; set; }
        public string id_userCreate { get; set; }
    }
}
