//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMatching
    {
        public int id { get; set; }
        public int id_MatchingType { get; set; }
        public int id_Debit_WorkBit { get; set; }
    
        public virtual Debit_MatchingType Debit_MatchingType { get; set; }
    }
}
