//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.PlanOrders = new HashSet<PlanOrders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string description { get; set; }
        public System.DateTime datetimeCreate { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string id_AspNetUsersGM { get; set; }
        public string id_AspNetUsersGE { get; set; }
        public double coefM { get; set; }
        public double coefE { get; set; }
        public double massa { get; set; }
        public int id_PZ_ProductType { get; set; }
        public bool remove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanOrders> PlanOrders { get; set; }
    }
}
