//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTask()
        {
            this.ProjectTask1 = new HashSet<ProjectTask>();
            this.ProjectTaskLinks = new HashSet<ProjectTaskLinks>();
            this.ProjectTaskLinks1 = new HashSet<ProjectTaskLinks>();
        }
    
        public int id { get; set; }
        public string id_TASK_WBS { get; set; }
        public string name { get; set; }
        public string sName { get; set; }
        public string description { get; set; }
        public bool taskIsSummary { get; set; }
        public int parentProjectTask { get; set; }
        public bool isActiveBP { get; set; }
        public Nullable<int> id_Devision { get; set; }
    
        public virtual Devision Devision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTask> ProjectTask1 { get; set; }
        public virtual ProjectTask ProjectTask2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTaskLinks> ProjectTaskLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTaskLinks> ProjectTaskLinks1 { get; set; }
    }
}
