//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServer_UpdateMustStartOn
    {
        public int id { get; set; }
        public System.Guid ProjectUID { get; set; }
        public System.Guid TaskUID { get; set; }
        public System.DateTime ActualStart { get; set; }
    }
}
