//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServer_UpdateTasks
    {
        public int id { get; set; }
        public Nullable<double> nk { get; set; }
        public Nullable<double> np { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<double> percentComplited { get; set; }
        public System.Guid projectUID { get; set; }
        public System.Guid taskUID { get; set; }
        public bool uploadData { get; set; }
    }
}
