//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public int Заказ { get; set; }
        public string Изделие { get; set; }
        public string Тр_р { get; set; }
        public string Модуль { get; set; }
        public string Заказчик { get; set; }
        public System.DateTime Договор { get; set; }
        public Nullable<System.DateTime> Отгрузка { get; set; }
        public Nullable<int> Откл_ { get; set; }
        public Nullable<double> С_С_1ед_ { get; set; }
        public Nullable<double> Договорная_цена { get; set; }
        public Nullable<double> Buj { get; set; }
        public Nullable<double> C__Бюджета { get; set; }
        public string Валюта { get; set; }
        public int id { get; set; }
    }
}
