//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServer_CreateTasks
    {
        public int id { get; set; }
        public System.Guid ProjectUID { get; set; }
        public string TaskName { get; set; }
        public int Work { get; set; }
        public string Resource { get; set; }
        public Nullable<int> Devision { get; set; }
        public bool update { get; set; }
    }
}
