//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWA_EmpTaskAll
    {
        public System.Guid TaskUID { get; set; }
        public Nullable<System.Guid> TaskParentUID { get; set; }
        public System.Guid ProjectUID { get; set; }
        public string TaskName { get; set; }
        public string TaskWBS { get; set; }
        public Nullable<decimal> TaskWork { get; set; }
        public Nullable<System.DateTime> TaskFinishDate { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<short> TaskPercentWorkCompleted { get; set; }
        public Nullable<int> PlanZakaz { get; set; }
        public Nullable<System.Guid> ResourceUID { get; set; }
        public string ResourceName { get; set; }
    }
}
