//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class PZ_FIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PZ_FIO()
        {
            this.PZ_PlanZakaz = new HashSet<PZ_PlanZakaz>();
        }
    
        public int id { get; set; }
        public string fio { get; set; }
        public string i { get; set; }
        public string o { get; set; }
        public int id_PZ_Client { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string position { get; set; }
    
        public virtual PZ_Client PZ_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PZ_PlanZakaz> PZ_PlanZakaz { get; set; }
    }
}
