//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation_Answer
    {
        public int id { get; set; }
        public int id_Reclamation { get; set; }
        public string id_AspNetUsersError { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string answer { get; set; }
        public System.DateTime dateTimeCreate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Reclamation Reclamation { get; set; }
    }
}
