//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation_Order
    {
        public int id { get; set; }
        public System.DateTime dateCreate { get; set; }
        public string userCreate { get; set; }
        public string userUpdate { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public int id_OTK_TypeReclamation { get; set; }
        public int id_Reclamation_WhoInc { get; set; }
        public int id_Reclamation_TypeDoc { get; set; }
        public string numberDoc { get; set; }
        public System.DateTime dateDoc { get; set; }
        public int id_PZ_Client { get; set; }
        public string textData { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public bool close { get; set; }
        public bool closeSMR { get; set; }
        public string userWork { get; set; }
    }
}
