//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation_Answer
    {
        public int id { get; set; }
        public int id_Reclamation { get; set; }
        public string id_AspNetUsersCreate { get; set; }
        public string answer { get; set; }
        public System.DateTime dateTimeCreate { get; set; }
        public bool trash { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Reclamation Reclamation { get; set; }
    }
}
