//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation_TechnicalAdviceProtocolPosition
    {
        public int id { get; set; }
        public int id_Reclamation_TechnicalAdvice { get; set; }
        public int id_Reclamation_TechnicalAdviceProtocol { get; set; }
    
        public virtual Reclamation_TechnicalAdvice Reclamation_TechnicalAdvice { get; set; }
        public virtual Reclamation_TechnicalAdviceProtocol Reclamation_TechnicalAdviceProtocol { get; set; }
    }
}
