//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReeportStatusPlanZakaz
    {
        public int id { get; set; }
        public string reportColumnName { get; set; }
        public bool active { get; set; }
        public bool activePO { get; set; }
        public Nullable<bool> activeGraphic { get; set; }
        public string graphicColumnName { get; set; }
    }
}
