//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RKD_Question()
        {
            this.RKD_QuestionData = new HashSet<RKD_QuestionData>();
        }
    
        public int id { get; set; }
        public int id_RKD_Order { get; set; }
        public System.DateTime dateUpload { get; set; }
        public string userUpload { get; set; }
        public string textQuestion { get; set; }
        public bool complited { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual RKD_Order RKD_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RKD_QuestionData> RKD_QuestionData { get; set; }
    }
}
