//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_TaskVersion
    {
        public int id { get; set; }
        public int id_RKD_Version { get; set; }
        public int id_RKD_Task { get; set; }
        public System.DateTime finishDate { get; set; }
        public bool tpComplited { get; set; }
        public bool allComplited { get; set; }
        public Nullable<bool> uslovnoeComplited { get; set; }
        public Nullable<bool> osComplited { get; set; }
        public Nullable<bool> manufComplited { get; set; }
    
        public virtual RKD_Task RKD_Task { get; set; }
        public virtual RKD_Version RKD_Version { get; set; }
    }
}
