//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_TaskUIDProjectUD
    {
        public System.Guid TaskUID { get; set; }
        public System.Guid ProjectUID { get; set; }
        public Nullable<decimal> RKD { get; set; }
    }
}
