//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_PostList
    {
        public int id { get; set; }
        public string email { get; set; }
        public int id_TypeRKD_Mail_Version { get; set; }
    
        public virtual TypeRKD_Mail_Version TypeRKD_Mail_Version { get; set; }
    }
}
