//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_FileMailVersion
    {
        public int id { get; set; }
        public int id_RKD_Mail_Version { get; set; }
        public System.DateTime dateTimeLastUpdateFile { get; set; }
        public string nameFile { get; set; }
    
        public virtual RKD_Mail_Version RKD_Mail_Version { get; set; }
    }
}
