//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_Version
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RKD_Version()
        {
            this.RKD_Mail_Version = new HashSet<RKD_Mail_Version>();
            this.RKD_TaskVersion = new HashSet<RKD_TaskVersion>();
        }
    
        public int id { get; set; }
        public int id_RKD_Order { get; set; }
        public int id_RKD_VersionWork { get; set; }
        public short numberVersion1 { get; set; }
        public short numberVersion2 { get; set; }
        public bool activeVersion { get; set; }
        public int id_RKD_VersionDay { get; set; }
        public Nullable<System.DateTime> planFinishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RKD_Mail_Version> RKD_Mail_Version { get; set; }
        public virtual RKD_Order RKD_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RKD_TaskVersion> RKD_TaskVersion { get; set; }
        public virtual RKD_VersionDay RKD_VersionDay { get; set; }
        public virtual RKD_VersionWork RKD_VersionWork { get; set; }
    }
}
