//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_DateAction
    {
        public Nullable<int> Заказ { get; set; }
        public string Версия { get; set; }
        public Nullable<System.DateTime> da { get; set; }
        public string name { get; set; }
        public Nullable<long> numberEctionOrderByDESCDateAction { get; set; }
        public Nullable<System.DateTime> Дата_отправки_первой_версии { get; set; }
    }
}
