//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKD_FailBPlan
    {
        public int id { get; set; }
        public System.Guid ProjectUID { get; set; }
        public string TaskName { get; set; }
        public string ResourceName { get; set; }
        public string СДРес { get; set; }
        public System.DateTime TaskFinishDate { get; set; }
        public System.DateTime TaskBaseline0FinishDate { get; set; }
        public double C_ { get; set; }
        public double TaskRemainingWork { get; set; }
    }
}
