//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_ReclamationCorrespondence
    {
        public int id { get; set; }
        public int id_Service_Reclamation { get; set; }
        public int id_Service_TypeCorrespondence { get; set; }
        public string link { get; set; }
        public System.DateTime dateUpload { get; set; }
    
        public virtual Service_Reclamation Service_Reclamation { get; set; }
        public virtual Service_TypeCorrespondence Service_TypeCorrespondence { get; set; }
    }
}
