//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_ReclamationMonthResult
    {
        public int id { get; set; }
        public int id_Service_ReclamationMonthDoc { get; set; }
        public int id_Service_ReclamationAnswerDevision { get; set; }
        public int id_Service_ReclamationCounterError { get; set; }
    
        public virtual Service_ReclamationAnswerDevision Service_ReclamationAnswerDevision { get; set; }
        public virtual Service_ReclamationCounterError Service_ReclamationCounterError { get; set; }
        public virtual Service_ReclamationMonthDoc Service_ReclamationMonthDoc { get; set; }
    }
}
