//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_ReclamationAnswerDevision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_ReclamationAnswerDevision()
        {
            this.Service_ReclamationMonthResult = new HashSet<Service_ReclamationMonthResult>();
        }
    
        public int id { get; set; }
        public int id_Service_Reclamation { get; set; }
        public int id_Devision { get; set; }
        public bool complited { get; set; }
        public System.DateTime dateTimeCreate { get; set; }
        public System.DateTime dateTimeLastUpdate { get; set; }
        public string userCreate { get; set; }
        public string userLastUpdate { get; set; }
        public string answerText { get; set; }
    
        public virtual Devision Devision { get; set; }
        public virtual Service_Reclamation Service_Reclamation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationMonthResult> Service_ReclamationMonthResult { get; set; }
    }
}
