//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_ReclamationAddOrder
    {
        public int id { get; set; }
        public int id_Service_Reclamation { get; set; }
        public string userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public string userLastUpdate { get; set; }
        public System.DateTime dateLastUpdate { get; set; }
        public string description { get; set; }
        public bool deactiveOrder { get; set; }
    
        public virtual Service_Reclamation Service_Reclamation { get; set; }
    }
}
