//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRemarksReclamations
    {
        public int id { get; set; }
        public int id_ServiceRemarks { get; set; }
        public int id_Reclamation { get; set; }
    
        public virtual Reclamation Reclamation { get; set; }
        public virtual ServiceRemarks ServiceRemarks { get; set; }
    }
}
