//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Reclamation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Reclamation()
        {
            this.Service_ReclamationAddOrder = new HashSet<Service_ReclamationAddOrder>();
            this.Service_ReclamationAnswerDevision = new HashSet<Service_ReclamationAnswerDevision>();
            this.Service_ReclamationCorrespondence = new HashSet<Service_ReclamationCorrespondence>();
            this.Service_ReclamationInfo = new HashSet<Service_ReclamationInfo>();
            this.Service_ReclamationPZ = new HashSet<Service_ReclamationPZ>();
            this.Service_ReclamationType = new HashSet<Service_ReclamationType>();
        }
    
        public int id { get; set; }
        public int id_Service_TypeDocument { get; set; }
        public System.DateTime dateAdd { get; set; }
        public int id_Service_ReclamationWhoAdd { get; set; }
        public string numberDocument { get; set; }
        public System.DateTime dateDocument { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public bool addMission { get; set; }
    
        public virtual Service_ReclamationWhoAdd Service_ReclamationWhoAdd { get; set; }
        public virtual Service_TypeReclamationDocument Service_TypeReclamationDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationAddOrder> Service_ReclamationAddOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationAnswerDevision> Service_ReclamationAnswerDevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationCorrespondence> Service_ReclamationCorrespondence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationInfo> Service_ReclamationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationPZ> Service_ReclamationPZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ReclamationType> Service_ReclamationType { get; set; }
    }
}
