//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetInformation
    {
        public string ENTRY { get; set; }
        public Nullable<int> SheetType { get; set; }
        public Nullable<int> LayoutType { get; set; }
        public byte[] HorzLayout { get; set; }
        public byte[] VertLayout { get; set; }
        public string Orientation { get; set; }
        public byte[] DrawingArea { get; set; }
        public byte[] PRINT_AREA { get; set; }
    }
}
