//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public Nullable<short> C_ { get; set; }
        public string C__заказа { get; set; }
        public string Название_задачи { get; set; }
        public Nullable<System.DateTime> Окончание { get; set; }
        public Nullable<System.DateTime> Дата_отгрузки { get; set; }
        public int dataRezresheniyaProizvodstva { get; set; }
        public Nullable<System.DateTime> П_Ведомость_в_1с__КБМ_ { get; set; }
        public Nullable<System.DateTime> П_Ведомость_в_1с__КБЭ_ { get; set; }
        public int id { get; set; }
    }
}
