//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SKU()
        {
            this.IlliquidAddStock = new HashSet<IlliquidAddStock>();
            this.IlliquidChangeInTheNorm = new HashSet<IlliquidChangeInTheNorm>();
            this.IlliquidNorm = new HashSet<IlliquidNorm>();
            this.IlliquidOrders = new HashSet<IlliquidOrders>();
            this.IlliquidRelease = new HashSet<IlliquidRelease>();
            this.IlliquidReplacement = new HashSet<IlliquidReplacement>();
            this.IlliquidReplacement1 = new HashSet<IlliquidReplacement>();
            this.IlliquidSN = new HashSet<IlliquidSN>();
            this.IlliquidStockState = new HashSet<IlliquidStockState>();
        }
    
        public int id { get; set; }
        public string designation { get; set; }
        public string name { get; set; }
        public string indexMaterial { get; set; }
        public int sku1 { get; set; }
        public double weight { get; set; }
        public double WeightR { get; set; }
        public double WeightArmis { get; set; }
        public string Note { get; set; }
        public string XMLCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidAddStock> IlliquidAddStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidChangeInTheNorm> IlliquidChangeInTheNorm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidNorm> IlliquidNorm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidOrders> IlliquidOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidRelease> IlliquidRelease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidReplacement> IlliquidReplacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidReplacement> IlliquidReplacement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidSN> IlliquidSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlliquidStockState> IlliquidStockState { get; set; }
    }
}
