//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slots
    {
        public string Entry { get; set; }
        public int Copy { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RetainingRailType { get; set; }
        public Nullable<double> x1 { get; set; }
        public Nullable<double> y1 { get; set; }
        public Nullable<double> z1 { get; set; }
        public Nullable<double> x2 { get; set; }
        public Nullable<double> y2 { get; set; }
        public Nullable<double> z2 { get; set; }
        public Nullable<double> Width { get; set; }
    }
}
