//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVNLast120
    {
        public int id { get; set; }
        public int year { get; set; }
        public string quart { get; set; }
        public string month { get; set; }
        public double data { get; set; }
    }
}
