//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMBOL_STATES
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string SYMBOL_ID { get; set; }
        public string FU_STATE_ID { get; set; }
        public int FUSUBID { get; set; }
        public Nullable<int> ORDER_NUM { get; set; }
        public Nullable<int> FLAGS { get; set; }
    }
}
