//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolGraphic
    {
        public string ENTRY { get; set; }
        public int COPY { get; set; }
        public Nullable<int> GraphicType { get; set; }
        public Nullable<int> Linecolor { get; set; }
        public Nullable<int> Linetype { get; set; }
        public Nullable<double> Linewidth { get; set; }
        public Nullable<int> Fillmode { get; set; }
        public Nullable<int> Fillcolor { get; set; }
        public byte[] HatchData { get; set; }
        public byte[] GraphicData { get; set; }
        public Nullable<int> GraphicLevel { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> ID { get; set; }
        public string STATE_ID { get; set; }
    }
}
