//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolDimension
    {
        public string ENTRY { get; set; }
        public Nullable<double> LSHX1 { get; set; }
        public Nullable<double> LSHY1 { get; set; }
        public Nullable<double> LSHX2 { get; set; }
        public Nullable<double> LSHY2 { get; set; }
    }
}
