//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolNodes
    {
        public string ENTRY { get; set; }
        public int COPY { get; set; }
        public Nullable<int> LIBNTY { get; set; }
        public Nullable<double> LIBNX { get; set; }
        public Nullable<double> LIBNY { get; set; }
        public Nullable<int> LBSTUB { get; set; }
        public Nullable<int> LBNNUM { get; set; }
        public Nullable<int> Function { get; set; }
    }
}
