//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolData
    {
        public string ID { get; set; }
        public string ENTRY { get; set; }
        public string VERSION { get; set; }
        public Nullable<int> Norm { get; set; }
        public string LSHDES { get; set; }
        public Nullable<int> LSHTYP { get; set; }
        public Nullable<int> ENTRYTYP { get; set; }
        public string LPNTR { get; set; }
        public string VSTATUS { get; set; }
        public string VersionText { get; set; }
        public Nullable<System.DateTime> DATEMAIN { get; set; }
        public Nullable<System.DateTime> LASTUPDT { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public Nullable<int> SYMINDEX { get; set; }
        public Nullable<int> FLAGS2 { get; set; }
        public Nullable<int> FLAGS { get; set; }
    }
}
