//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolText
    {
        public string ENTRY { get; set; }
        public int COPY { get; set; }
        public Nullable<int> TTYPE { get; set; }
        public Nullable<double> TX { get; set; }
        public Nullable<double> TY { get; set; }
        public Nullable<int> TJUST { get; set; }
        public Nullable<double> THT { get; set; }
        public Nullable<int> TMOD { get; set; }
        public Nullable<int> TLEV { get; set; }
        public string TSTR { get; set; }
        public Nullable<int> LBNNUM { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<double> TROT { get; set; }
        public string FontName { get; set; }
        public Nullable<int> FontStyle { get; set; }
        public Nullable<int> TextColor { get; set; }
        public Nullable<int> Flags2 { get; set; }
        public Nullable<double> SIZEX { get; set; }
        public Nullable<double> SIZEY { get; set; }
        public string Hyperlink { get; set; }
    }
}
