//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMBOL_FUNCTION
    {
        public string LPNTR { get; set; }
        public int LBNNUM { get; set; }
        public int FUSUBID { get; set; }
        public string FUNAME { get; set; }
        public Nullable<int> FUID { get; set; }
        public Nullable<int> FUPORT { get; set; }
    }
}
