//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOInWorkPOGroupBy
    {
        public string Месяц { get; set; }
        public Nullable<decimal> тр_ты { get; set; }
        public Nullable<double> ХВыручка { get; set; }
        public Nullable<double> ХСС { get; set; }
        public Nullable<double> ХССФакт { get; set; }
        public Nullable<double> ХССЗП { get; set; }
        public Nullable<double> ХИК { get; set; }
        public Nullable<double> ХППК { get; set; }
        public Nullable<double> ХПИ { get; set; }
        public Nullable<double> ХНОП { get; set; }
        public Nullable<double> ХССЗПФакт { get; set; }
        public Nullable<double> RSSM { get; set; }
        public Nullable<double> RSSMF { get; set; }
    }
}
