//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEOInWorkPO
    {
        public string Месяц { get; set; }
        public string quart { get; set; }
        public string Неделя { get; set; }
        public Nullable<int> year { get; set; }
        public string C__заказа { get; set; }
        public string Название_задачи { get; set; }
        public Nullable<System.DateTime> TimeByDay { get; set; }
        public Nullable<decimal> AssignmentWork { get; set; }
        public string СДРес { get; set; }
        public Nullable<decimal> КПО { get; set; }
        public Nullable<double> Выручка_без_НДС { get; set; }
        public Nullable<double> С_С_материалов { get; set; }
        public Nullable<double> С_С_материалов___факт1с { get; set; }
        public Nullable<double> С_С_зп_рабочих { get; set; }
        public Nullable<double> Издержки_коммерческие { get; set; }
        public Nullable<double> C__по_кредиту { get; set; }
        public Nullable<double> Постоянные_издержки { get; set; }
        public Nullable<double> НОП { get; set; }
        public Nullable<double> С_С_зп_рабочих___фактХТЭО { get; set; }
        public Nullable<double> Выручка_без_НДС_1ч_ПО { get; set; }
        public Nullable<double> С_С_материалов_1ч_ПО { get; set; }
        public Nullable<double> С_С_материалов___факт1с_1ч_ПО { get; set; }
        public Nullable<double> С_С_зп_рабочих_1ч_ПО { get; set; }
        public Nullable<double> Издержки_коммерческие_1ч_ПО { get; set; }
        public Nullable<double> C__по_кредиту_1ч_ПО { get; set; }
        public Nullable<double> Постоянные_издержки_1ч_ПО { get; set; }
        public Nullable<double> НОП_1ч_ПО { get; set; }
        public Nullable<double> С_С_зп_рабочих___фактХТЭО_1ч_ПО { get; set; }
        public Nullable<double> ХВыручка { get; set; }
        public Nullable<double> ХСС { get; set; }
        public Nullable<double> ХССФакт { get; set; }
        public Nullable<double> ХССЗП { get; set; }
        public Nullable<double> ХИК { get; set; }
        public Nullable<double> ХППК { get; set; }
        public Nullable<double> ХПИ { get; set; }
        public Nullable<double> ХНОП { get; set; }
        public Nullable<double> ХССЗПФакт { get; set; }
        public int id { get; set; }
        public Nullable<double> RSSM { get; set; }
        public Nullable<double> RSSMF { get; set; }
    }
}
