//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class TierMap
    {
        public int id { get; set; }
        public int tierIdStart { get; set; }
        public int tierIdFinish { get; set; }
        public double distance { get; set; }
    
        public virtual Tier Tier { get; set; }
        public virtual Tier Tier1 { get; set; }
    }
}
