//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class VV_Position
    {
        public int id { get; set; }
        public int id_VVPZ { get; set; }
        public int numMesto { get; set; }
        public string Gabarit { get; set; }
        public string Description { get; set; }
        public int massaBrutto { get; set; }
        public int massaNetto { get; set; }
    
        public virtual VVPZ VVPZ { get; set; }
    }
}
