//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVPZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VVPZ()
        {
            this.VV_Position = new HashSet<VV_Position>();
        }
    
        public int id { get; set; }
        public int id_PZ_PlanZakaz { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> massaBrutto { get; set; }
        public Nullable<int> massaNetto { get; set; }
        public string gruzopoluchatel { get; set; }
        public string adresGruzo { get; set; }
        public string iNNGruz { get; set; }
        public string oKPOGruz { get; set; }
        public string kodGruz { get; set; }
        public string sTNazn { get; set; }
        public string kodSt { get; set; }
        public string osobieOtm { get; set; }
        public string prochee { get; set; }
        public Nullable<System.DateTime> dateSh { get; set; }
    
        public virtual PZ_PlanZakaz PZ_PlanZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VV_Position> VV_Position { get; set; }
    }
}
