//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTEO
    {
        public int id { get; set; }
        public int planZakaz { get; set; }
        public System.DateTime dateShip { get; set; }
        public double viruchka { get; set; }
        public double oChena { get; set; }
        public double izKom { get; set; }
        public double percKredit { get; set; }
        public double ssm { get; set; }
        public double fssm { get; set; }
        public double sspo { get; set; }
        public double fsspo { get; set; }
        public double curency { get; set; }
        public double pi { get; set; }
        public string valut { get; set; }
        public System.DateTime dateOpen { get; set; }
    }
}
